unique_ids:
  forms:
    Form1: JSOACXZNM7NHWP3RAYZ6LF5N3CEE3SJE
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: BAVHTPRBAUFW5AQ6OJNVMHUW7VKXL3CO
    theme.css: CPVNMDALYYMCCPZVAARHCDSBYAPI7SVG
